billingsystem/accounting/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('ledgerdetailpage/<str:pk>/', views.customer_ledger_detail_page, name="ledgerdetailpage"),
    path('ledger/', views.save_customer_ledger_details, name="ledger"),
    path('create_ledger/<str:pk>/', views.create_ledger, name="create_ledger"),
    path('delete_ledger/<str:pk>/', views.delete_ledger_detail, name="delete_ledger"),
    path('update_ledger/<str:pk>/', views.update_ledger_detail, name="update_ledger"),
    path('invoice', views.invoice, name="invoice"),
    path('invoicedetail', views.invoice_detail, name="invoicedetail"),
    path('billupdate/<str:pk>/', views.update_invoice, name="billupdate"),
    path('billdelete/<str:pk>/', views.delete_invoice, name="billdelete"),
]

billingsystem/billingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billingsystem/accounting/models.py
from django.db import models


class Ledger(models.Model):
    c_name = models.CharField(max_length=500, null=True)
    c_code = models.CharField(max_length=200, null=True, blank=True)
    c_date_form_start = models.DateField(null=True, blank=True)
    c_date_form_end = models.DateField(null=True, blank=True)

    def __str__(self):
        if self.c_name == None:
            return "Empty!! Name is not inserted"
        return self.c_name


class ledger_description(models.Model):
    c_description = models.CharField(max_length=200, null=True, blank=True)
    c_current_date = models.DateField(null=True, blank=True, default="-")
    c_debt_amt = models.FloatField(null=True, default='0')
    c_credit_amt = models.FloatField(null=True, default='0')
    ledgerDetail = models.ForeignKey(Ledger, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        if self.c_description == None:
            return "Empty!! Description is not inserted"
        return self.c_description


class Customer(models.Model):
    PAYMENT_CHOICES = (
        ("1", "Cash"),
        ("2", "Credit"),
        ("3", "Card"),
    )
    customer_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    pan_no = models.CharField(max_length=200)
    invoice_no = models.CharField(max_length=200, unique=True)
    invoice_date = models.DateField()
    payment_mode = models.CharField(choices=PAYMENT_CHOICES, max_length=50)
    subtotal = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2)
    taxable_amount = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    vat = models.DecimalField(max_digits=20, decimal_places=2)
    total_amount = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    in_words = models.CharField(max_length=500, blank=True, null=True)
    remarks = models.CharField(max_length=500, blank=True, null=True)
    received_by = models.CharField(max_length=200, blank=True, null=True)
    prepared_by = models.CharField(max_length=200)
    authorized_sign = models.CharField(max_length=200, blank=True, null=True)
    date_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.customer_name


class Bill(models.Model):
    item_no = models.CharField(max_length=10, blank=True, null=True)
    particular = models.CharField(max_length=200, blank=True, null=True)
    alt_qty = models.IntegerField(default=0, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    Uom = models.CharField(max_length=100, blank=True, null=True)
    rate = models.DecimalField(decimal_places=2, max_digits=20, blank=True, null=True)
    discount = models.DecimalField(default=0, decimal_places=2, max_digits=20, blank=True, null=True)
    amount = models.DecimalField(default=0, decimal_places=2, max_digits=20, blank=True, null=True)
    invoice_no = models.ForeignKey(Customer, related_name='invoice', on_delete=models.CASCADE)

    def __str__(self):
        return self.item_no

billingsystem/accounting/forms.py
from django.forms import ModelForm, TextInput, DateInput, NumberInput
from django import forms
import datetime
from .models import *
from django.core.exceptions import NON_FIELD_ERRORS

class LedgerForm(ModelForm):
    class Meta:
        model = Ledger
        fields = ['c_name', 'c_date_form_start', 'c_date_form_end', ]
        # fields =  '__all__'
        widgets = {
            'c_name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 500px;',
                'placeholder': 'Enter Your Name',

            }),
            'c_date_form_start': DateInput(attrs={
                'type': 'date',
                'class': "form-control",
                'style': 'max-width: 500px;',
                'placeholder': 'mm/dd/yyyy',
                'required': True,
            }),
            'c_date_form_end': DateInput(attrs={
                'type': 'date',
                'class': "form-control",
                'style': 'max-width: 500px;',
                'placeholder': 'mm/dd/yyyy',
                'required': True,
            })

        }


class ledger_descriptionForm(ModelForm):
    class Meta:
        model = ledger_description
        fields = ['c_description', 'c_current_date', 'c_debt_amt', 'c_credit_amt', ]
        widgets = {
            'c_description': TextInput(attrs={
                'placeholder': 'Enter Your Description',
                'class': 'rounded border-success',
            }),

            'c_current_date': DateInput(attrs={
                'type': 'date',
                'placeholder': 'mm/dd/yyyy',
                'class': 'rounded border-primary',
            }),
            'c_debt_amt': NumberInput(attrs={
                'class': 'rounded border-secondary',
                'min': '0'
            }),
            'c_credit_amt': NumberInput(attrs={
                'class': 'rounded border-warning',
                'min': '0'
            }),

        }


PAYMENT_CHOICES = (
    ("1", "Cash"),
    ("2", "Credit"),
    ("3", "Card"),
)


class CustomerForm(forms.ModelForm):
    date_time = forms.DateTimeField(initial=datetime.datetime.now, disabled=True)
    class Meta:
        model = Customer

        fields = [
            'customer_name',
            'address',
            'phone',
            'pan_no',
            'invoice_no',
            'invoice_date',
            'payment_mode',
            'subtotal',
            'discount',
            'taxable_amount',
            'vat',
            'total_amount',
            'in_words',
            'remarks',
            'received_by',
            'prepared_by',
            'authorized_sign',
        ]

        widgets = {
            'customer_name': forms.TextInput(attrs={'style': 'width: 220px;' 'height: 30px;'}),
            'address': forms.TextInput(attrs={'style': 'width: 220px;' 'height: 30px;'}),
            'phone': forms.TextInput(attrs={'style': 'width: 220px;' 'height: 30px;'}),
            'pan_no': forms.TextInput(attrs={'style': 'width: 220px;' 'height: 30px;'}),
            'invoice_no': forms.TextInput(attrs={'placeholder': 'Enter Unique No','style': 'width: 160px;' 'height: 30px;'}),
            'invoice_date': forms.DateInput(attrs={'type': 'date', 'style': 'width: 160px;' 'height: 30px;'}),
            'payment_mode': forms.Select(choices=PAYMENT_CHOICES),
            'subtotal': forms.NumberInput(attrs={'style': 'width: 150px;' 'height: 30px;'}),
            'discount': forms.NumberInput(attrs={'style': 'width: 150px;' 'height: 30px;'}),
            'taxable_amount': forms.NumberInput(attrs={'readonly':'readonly','style': 'width: 150px;' 'height: 30px;'}),
            'vat': forms.NumberInput(attrs={'readonly':'readonly','style': 'width: 150px;' 'height: 30px;'}),
            'total_amount': forms.NumberInput(attrs={'readonly':'readonly','style': 'width: 150px;' 'height: 30px;'}),
            'in_words': forms.TextInput(attrs={'style': 'width: 500px;' 'height: 30px;'}),
            'remarks': forms.Textarea(attrs={'style': 'width: 500px;' 'height: 30px;'}),
            'received_by': forms.TextInput(attrs={'style': 'width: 180px;' 'height: 30px;'}),
            'prepared_by': forms.TextInput(attrs={'style': 'width: 180px;' 'height: 30px;'}),
            'authorized_sign': forms.TextInput(
                attrs={'style': 'width: 180px;' 'height: 30px;'}),
        }


class ItemForm(forms.ModelForm):
    class Meta:
        model = Bill

        fields = [
            'item_no',
            'particular',
            'alt_qty',
            'quantity',
            'Uom',
            'rate',
            'discount',
            'amount',
        ]

        widgets = {
            'item_no': forms.TextInput(attrs={'class': 'formset-field','style': 'width: 50px;' 'height: 30px;'}),
            'particular': forms.Textarea(attrs={'class': 'formset-field', 'style': 'width: 250px;' 'height: 30px;'}),
            'alt_qty': forms.TextInput(attrs={'class': 'formset-field', 'style': 'width: 80px;' 'height: 30px;'}),
            'quantity': forms.TextInput(attrs={'class': 'formset-field', 'style': 'width: 80px;' 'height: 30px;'}),
            'Uom': forms.TextInput(attrs={'class': 'formset-field', 'style': 'width: 70px;' 'height: 30px;'}),
            'rate': forms.NumberInput(attrs={'class': 'formset-field', 'style': 'width: 110px;' 'height: 30px;'}),
            'discount': forms.NumberInput(attrs={'class': 'formset-field', 'style': 'width: 110px;' 'height: 30px;'}),
            'amount': forms.NumberInput(attrs={'class': 'formset-field', 'style': 'width: 110px;' 'height: 30px;'}),
        }

billingsystem/accounting/views.py
from email import message
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CustomerForm, ItemForm
from django.forms import modelformset_factory
from .models import *
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from .forms import *
from django.db import transaction, IntegrityError
from django.contrib import messages



# Create your views here.
def home(request):
    context = {}
    return render(request, 'accounting/index.html', context)


def customer_ledger_detail_page(request, pk):
    customer_ledger = Ledger.objects.get(id=pk)
    customer_ledger_details = customer_ledger.ledger_description_set.all()

    context = {'customer_ledger': customer_ledger, 'customer_ledger_details': customer_ledger_details}
    return render(request, 'accounting/ledgerdetailpage.html', context)


def save_customer_ledger_details(request):
    ledger_d = Ledger.objects.all()
    LedgerForms = LedgerForm()

    if request.method == "POST":
        # print("pf : ", request.POST)
        form = LedgerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ledger')

    context = {'ledger_d': ledger_d, 'LedgerForms': LedgerForms, }

    return render(request, 'accounting/ledger.html', context)


def create_ledger(request, pk):
    ledger_descriptionFormSet = inlineformset_factory(Ledger, ledger_description, ledger_descriptionForm, extra=10,
                                                      can_delete=False)
    ledger = Ledger.objects.get(id=pk)
    formset = ledger_descriptionFormSet(queryset=ledger_description.objects.none(), instance=ledger)

    if request.method == 'POST':
        formset = ledger_descriptionFormSet(request.POST, instance=ledger)
        if formset.is_valid():
            formset.save()
            return redirect('/ledger')

    context = {'formset': formset, 'ledger': ledger}
    return render(request, 'accounting/createledger.html', context)


def update_ledger_detail(request, pk):
    ledger = ledger_description.objects.get(id=pk)

    formset = ledger_descriptionForm(instance=ledger, )

    if request.method == 'POST':
        formset = ledger_descriptionForm(request.POST, instance=ledger)
        if formset.is_valid():
            formset.save()
            return redirect('/update_ledger/' + str(ledger.pk))
    context = {'formset': formset, 'ledger': ledger}

    return render(request, 'accounting/updateledger.html', context)


def delete_ledger_detail(request, pk):
    ledgerDescription = ledger_description.objects.get(id=pk)

    if request.method == "POST":
        ledgerDescription.delete()
        return redirect('/ledger')

    context = {'item': ledgerDescription}
    return render(request, 'accounting/delete.html', context)


def invoice(request):
    context = {}
    ItemFormSet = modelformset_factory(Bill, form=ItemForm, extra=8)
    customerform = CustomerForm(request.POST or None)
    itemform = ItemFormSet(request.POST or None, queryset=Bill.objects.none())
    if request.method == 'POST':
        if itemform.is_valid() and customerform.is_valid():
            try:
                with transaction.atomic():
                    customer = customerform.save(commit=False)
                    customer.save()
                    for item in itemform:
                        data = item.save(commit=False)
                        data.invoice_no = customer
                        data.save()
                    messages.success(request, 'Bill saved successfully')   
            except IntegrityError:
                messages.error(request, 'Data entered is not correct')
            return redirect("/invoice")
        else:
            messages.error(request, 'Data entered is not correct or invoice number is not unique')
    else:
        context = {'iform':itemform, 'form':customerform}
    return render(request, 'accounting/bill.html', context)

def invoice_detail(request):
    data = Customer.objects.filter().order_by('-id')
    return render(request, 'accounting/invoicedetail.html',{'customerdetail':data})

def update_invoice(request, pk):
    data = Customer.objects.get(id=pk)
    bill = data.invoice.all()
    return render(request, 'accounting/billupdate.html', {'form':data, 'iform':bill})

def delete_invoice(request, pk):
    data = Customer.objects.get(id=pk)
    data.delete()
    messages.success(request, "Customer invoice deleted successfully" )
    return redirect("/invoicedetail")

billingsystem/accounting/templates/accounting/bill.html
{% extends 'accounting/main.html' %}
{% load static %}
{% block content %}
{% include 'accounting/navigation.html' %}
<html>
<head>
    <title>Tax Invoice</title>
    <style>
        body {
            background-color: #F6F6F6;
            margin: 0;
            padding: 0;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            margin: 0;
            padding: 0;
        }

        p {
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin-right: auto;
            margin-left: auto;
        }

        .brand-section {
            background-color: #1a2491;
            padding: 10px 10px;
        }

        .logo {
            width: 50%;
        }

        .row {
            display: flex;
            flex-wrap: wrap;
        }

        .col-6 {
            width: 50%;
            flex: 0 0 auto;
        }

        .text-white {
            color: #000;
        }

        .company-details {
            float: right;
            text-align: center;
        }

        .body-section {
            padding: 20px;
            border: 1px solid gray;
        }

        .heading {
            font-size: 15px;
            margin-bottom: 08px;
        }

        .sub-heading {
            color: #262626;
            margin-bottom: 05px;
        }

        table {
            background-color: #fff;
            width: 100%;
            border-collapse: collapse;
        }

        table thead tr {
            border: 1px solid #111;
            background-color: #f2f2f2;
        }

        table td {
            vertical-align: middle !important;
            text-align: center;
        }

        table th,
        table td {
            padding: 2px;
            text-align: center;
        }

        .table-bordered {
            box-shadow: 0px 0px 0px 0.5px gray;
        }

        .table-bordered td,
        .table-bordered th {
            border: 1px solid #dee2e6;
        }

        .text-right {
            text-align: end;
        }

        .w-20 {
            width: 20%;
        }

        .i-10 {
            width: 10%;
        }

        .float-right {
            float: right;
        }

        .float-left {
            margin: 5px;
            padding-top: 5px;
            padding-bottom: 5px;
            padding-right: 5px;
            padding-left: 20px;
        }

        .button {
            margin: 5px;
            padding: 5px;
        }

        @media print {
            #printbutton, #savebutton {
              display: none;
            }
          }
    </style>
</head>
<body>
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
    </div>
    {% endfor %}
    <form method="post" id="form-container" enctype="multipart/form-data">
        {% csrf_token %}
        {{ iform.management_form }}
        {{ form.non_field_errors}}
        <div class="container">
            <div class="action-buttons">
                <a type="button" id="printbutton" onclick="javascript:window.print()" value="Print"> <i class="mr-1 fa fa-print text-primary-m1 text-120 w-2"></i></a>
            </div>
            <div class="brand-section">
                <div class="row">
                    <div class="col-6">
                        <h1 class="text-white">TAX INVOICE</h1>
                        <h3 class="text-white">VAT NO:606678199</h3>
                    </div>
                    <div class="col-6">
                        <div class="company-details">
                            <h3 class="text-white">DV Trading PVT.LTD</h3>
                            <p class="text-white">Head office-Janakpur-04 Dhanusha</p>
                            <p class="text-white">Branch office-Kuleshwor-14 Kathmandu</p>
                            <p class="text-white">Contact No: 977-1-4285484, 4287358</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="body-section">
                <div class="row">
                    <div class="col-6">
                        {{ form.customer_name.errors }}
                        <p class="sub-heading">Customer Name: {{ form.customer_name }} </p>
                        {{ form.address.errors }}
                        <p class="sub-heading">Address: {{ form.address }} </p>
                        {{ form.phone.errors }}
                        <p class="sub-heading">Phone Number: {{ form.phone }} </p>
                        {{ form.pan_no.errors }}
                        <p class="sub-heading">VAT/PAN No: {{ form.pan_no }} </p>
                    </div>
                    <div class="col-6">
                        {{ form.invoice_no.errors }}
                        <p class="sub-heading">Invoice No:{{ form.invoice_no }} </p>
                        {{ form.invoice_date.errors }}
                        <p class="sub-heading">Invoice Date: {{ form.invoice_date }}</p>
                        {{ form.payment_mode.errors }}
                        <p class="sub-heading">Payment Mode: {{ form.payment_mode }}</p>
                    </div>
                </div>
            </div>

            <div class="body-section" >
                <!-- <h3 class="heading">Items</h3>
            <br> -->
                <table class="table-bordered">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Particular</th>
                            <th class="i-10">Alt Qty</th>
                            <th class="i-10">Quantity</th>
                            <th class="i-10">Uom</th>
                            <th class="i-10">Rate</th>
                            <th class="i-10">Discount</th>
                            <th class="i-10">Total Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for iforms in iform %}
                        <tr class="link-formset">
                            {{ iforms.item_no.errors}}
                            <td>{{ iforms.item_no }}</td>
                            {{ iforms.particular.errors}}
                            <td>{{ iforms.particular }}</td>
                            {{ iforms.alt_qty.errors }}
                            <td>{{ iforms.alt_qty }}</td>
                            {{ iforms.quantity.errors }}
                            <td>{{ iforms.quantity }}</td>
                            {{ iforms.Uom.errors }}
                            <td>{{ iforms.Uom }}</td>
                            {{ iforms.rate.errors }}
                            <td>{{ iforms.rate }}</td>
                            {{ iforms.discount.errors }}
                            <td>{{ iforms.discount }}</td>
                            {{ iforms.amount.errors }}
                            <td class="sum">{{ iforms.amount }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tbody>
                        <tr>
                            {{ form.subtotal.errors }}
                            <td colspan="7" class="text-right">Sub Total</td>
                            <td> {{form.subtotal}}</td>
                        </tr>
                        <tr>
                            {{ form.discount.errors }}
                            <td colspan="7" class="text-right">Discount</td>
                            <td> {{ form.discount }}</td>
                        </tr>
                        <tr>
                            {{ form.taxable_amount.errors }}
                            <td colspan="7" class="text-right">Taxable Amount</td>
                            <td> {{ form.taxable_amount }}</td>
                        </tr>
                        <tr>
                            {{ form.vat.errors }}
                            <td colspan="7" class="text-right">VAT 13%</td>
                            <td> {{ form.vat }}</td>
                        </tr>
                        <tr>
                            {{ form.total_amount.errors }}
                            <td colspan="7" class="text-right">Grand Total</td>
                            <td> {{ form.total_amount }}</td>
                        </tr>
                    </tbody>
                </table>
                <br>
                {{ form.in_words.errors }}
                <h6 class="heading">In Word: {{form.in_words}}</h6>
                {{ form.remarks.errors }}
                <h6 class="heading">Remark: {{form.remarks}}</h6>

            </div>
            <div class="row">
                {{ form.received_by.errors }}
                <div class="float-left">Received By: {{form.received_by}}
                </div>
                {{ form.prepared_by.errors }}
                <div class="float-left">Prepared By: {{form.prepared_by}}
                </div>
                {{ form.authorized_sign.errors }}
                <div class="float-left">Authorised Signature: {{form.authorized_sign}}
                </div>
                <input type="submit" id="savebutton" class="button" value="Save">
               
            </div>
            <div class="body-section">
                <p>Print Date & Time: {{ form.date_time }}
                </p>
            </div>
        </div>
    </form>

<script type="text/javascript">
    $('.link-formset').formset({
        addText: 'Add Item',
        deleteText: '-',
    });

    $(document).ready(function(){
    var id= $("#id_form-TOTAL_FORMS").val();
    console.log(id);
    for(let i=0; i < id; i++)
    {
    $("#id_form-"+i+"-quantity").keyup(function () {
        var rate = parseFloat($("#id_form-"+i+"-rate").val());
        var quantity = parseFloat($("#id_form-"+i+"-quantity").val());
        var discount = parseFloat($("#id_form-"+i+"-discount").val());
        $("#id_form-"+i+"-amount").val(rate * quantity - discount);
    });
    $("#id_form-"+i+"-rate").keyup(function () {
        var rate = parseFloat($("#id_form-"+i+"-rate").val());
        var quantity = parseFloat($("#id_form-"+i+"-quantity").val());
        var discount = parseFloat($("#id_form-"+i+"-discount").val());
        $("#id_form-"+i+"-amount").val(rate * quantity - discount);
    });
    $("#id_form-"+i+"-discount").keyup(function () {
        var rate = parseFloat($("#id_form-"+i+"-rate").val());
        var quantity = parseFloat($("#id_form-"+i+"-quantity").val());
        var discount = parseFloat($("#id_form-"+i+"-discount").val());
        $("#id_form-"+i+"-amount").val(rate * quantity - discount);
    
    });   
    //sum amount for subtotal
    $("#id_subtotal").click(function() {
        var total = 0;
        $("#id_form-"+i+"-amount").each(function(){
           total += +($(this).val());
        });
        console.log(total)
        $("#id_subtotal").val(total);
    });
}
});

    $("#id_discount").keyup(function () {
        var subtotal = parseFloat($("#id_subtotal").val());
        var discount = parseFloat($(this).val());
        $("#id_taxable_amount").val(subtotal - discount);
        $("#id_vat").val(parseFloat($("#id_taxable_amount").val()) * 13/100); 
        var tax= parseFloat($("#id_taxable_amount").val());
        var vat=  parseFloat($("#id_vat").val());
        $("#id_total_amount").val(tax + vat);
    });
</script>
</body>
</html>
{% endblock %}
    
<!-- $('#add_more').click(function() {
    var form_idx = $('#id_form-TOTAL_FORMS').val();
    $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
}); -->

billingsystem/accounting/templates/accounting/createledger.html
{% extends 'accounting/main.html' %}
{% load static %}

{% block content %}
{% include 'accounting/navigation.html'%}

<form action="" method="POST">
    {% csrf_token %}

    <h2>Ledger Creating Page</h2>
    <table class="table table-sm" style="text-align: center;">
        <tr>
            <th>Name: {{ledger.c_name}}
            <input class="btn btn-outline-info" type="submit" name="saveLedger" value="Save" style="float:right;">
            </th>
        </tr>
        {{ formset.management_form }}
        {% for form in formset %}
        <tr>
            <td>
                <b style="color: #dc3545;">*</b> <label>Description </label> &nbsp; &nbsp;
                {{form.c_description}}

 &nbsp; &nbsp; &nbsp;
                <b style="color: #dc3545;">*</b> <label>Date </label> &nbsp; &nbsp;
                {{form.c_current_date}}
 &nbsp; &nbsp; &nbsp;
                <b style="color: #dc3545;">*</b> <label>Debit Amount </label> &nbsp; &nbsp;
                {{form.c_debt_amt}}
 &nbsp; &nbsp; &nbsp;
                <b style="color: #dc3545;">*</b> <label>Credit Amount </label> &nbsp; &nbsp;
                {{form.c_credit_amt}}

            </td>
        </tr>
        {% endfor %}

    </table>

</form>

{% endblock %}

billingsystem/accounting/templates/accounting/delete.html
{% extends 'accounting/main.html' %}
{% load static %}

{% block content %}
{% include 'accounting/navigation.html'%}


 <form method="post" action="">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{item}}"?</p>
                    <a class="btn btn-warning" href="#">Cancel</a>

                    <input class="btn btn-danger" type="submit" name="Confirm">
                </form>


{% endblock %}

billingsystem/accounting/templates/accounting/index.html
{% extends 'accounting/main.html' %}
{% load static %}

{% block content %}
{% include 'accounting/navigation.html'%}

        <h2>Sidenav Push Example</h2>
        <p>Click on the element below to open the side navigation menu, and push this content to the right.</p>

{% endblock %}

billingsystem/accounting/templates/accounting/invoicedetail.html
{% extends 'accounting/main.html' %}
{% load static %}
{% block content %}
{% include 'accounting/navigation.html' %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
    </div>
    {% endfor %}
    <h2>Invoice List</h2>
    
    <table>
      <tr>
        <th>Customer Name</th>
        <th>Invoice No</th>
        <th>PAN</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Total Amount</th>
        <th>Payment Mode</th>
        <th>Prepared By</th>
        <th>Date & Time</th>
        <th>View Invoice</th>
        <th>Delete</th>
      </tr>
      {% for cust in customerdetail %}
      <tr>
        <td>{{ cust.customer_name }}</td>
        <td>{{ cust.invoice_no }}</td>
        <td>{{ cust.pan_no }}</td>
        <td>{{ cust.address }}</td>
        <td>{{ cust.phone }}</td>
        <td>{{ cust.total_amount }}</td>
        <td>{{ cust.get_payment_mode_display }}</td>
        <td>{{ cust.prepared_by }}</td>
        <td>{{ cust.date_time }}</td>
        <td><a href="{% url 'billupdate' cust.id %}"><i class="fa fa-upload"
          style="font-size:24px; color:#32cd32"></i></a></td>
        <td><a class="confirm-delete" href="{% url 'billdelete' cust.id %}"><i class="fa fa-trash-o"
          style="font-size:28px;color:red"> </i>
        </a></td>
      </tr>
      {% endfor %}
    </table>
  <script>
    $(document).on('click', '.confirm-delete', function(){
    return confirm('Are you sure you want to delete this customer detail?');
    })
  </script>
{% endblock %}

billingsystem/accounting/templates/accounting/navigation.html
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()" style="text-decoration: none;">&times;</a>
    <a href="/" style="text-decoration: none;">Home</a>
    <a href="/invoice" style="text-decoration: none;">Invoice</a>
    <a href="/invoicedetail" style="text-decoration: none;">Invoice List</a>
    <a href="{% url 'ledger' %}" style="text-decoration: none;">Ledger</a>
    <a href="#" style="text-decoration: none;">Contact</a>
    <a href="#" style="text-decoration: none;">About</a>
</div>